### ISSUE TITLE
Install on Raspberry PI

### ISSUE THREAD

**Issue by BobFIV** [agoose77/jupyterlab-markup#6]
The install build process fails. I am not sure how resolve this.

pi@raspberrypi:~ $ sudo jupyter labextension install @agoose77/jupyterlab-markup               Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-vvjmi75o.log

pi@raspberrypi:~ $ sudo cat /tmp/jupyterlab-debug-vvjmi75o.log 
Node v10.15.2

Yarn configuration loaded.
> /usr/local/bin/npm pack @agoose77/jupyterlab-markup
npm notice 
npm notice 📦  @agoose77/jupyterlab-markup@0.2.1
npm notice === Tarball Contents === 
npm notice 1.6kB package.json      
npm notice 1.3kB README.md         
npm notice 238B  lib/factories.d.ts
npm notice 384B  lib/factories.js  
npm notice 145B  lib/index.d.ts    
npm notice 759B  lib/index.js      
npm notice 1.6kB lib/renderers.d.ts
npm notice 2.4kB lib/renderers.js  
npm notice 921B  lib/widgets.d.ts  
npm notice 2.7kB lib/widgets.js    
npm notice === Tarball Details === 
npm notice name:          @agoose77/jupyterlab-markup             
npm notice version:       0.2.1                                   
npm notice filename:      agoose77-jupyterlab-markup-0.2.1.tgz    
npm notice package size:  4.0 kB                                  
npm notice unpacked size: 12.0 kB                                 
npm notice shasum:        788f249c5c18ca3d145d35219e42821d2834669c
npm notice integrity:     sha512-P3J6fsHWOCqu4[...]NgOW7zswGblSw==
npm notice total files:   10                                      
npm notice 
agoose77-jupyterlab-markup-0.2.1.tgz

Node v10.15.2

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /usr/local/lib/python3.7/dist-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 2.66s.

> node /usr/local/lib/python3.7/dist-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /usr/local/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 3.12s.

> node /usr/local/lib/python3.7/dist-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
/usr/bin/node[1493]: ../src/node_platform.cc:414:std::shared_ptr<node::PerIsolatePlatformData> node::NodePlatform::ForIsolate(v8::Isolate*): Assertion `data' failed.
child_process.js:637
    throw err;
    ^

Error: Command failed: /usr/local/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:616:11)
    at Object.execFileSync (child_process.js:634:13)
    at Object.<anonymous> (/usr/local/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "/usr/local/lib/python3.7/dist-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
pi@raspberrypi:~ $

**Comment by agoose77** [comment]
I don't think this is an error in this extension. It looks like an issue
related to node and arm - https://github.com/nodejs/node/issues/21562

**Comment by agoose77** [comment]
I'm closing this issue as it is a JupyterLab / nodejs problem :)
